import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Tabs } from 'antd';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Tabs
          items={[
            {
              label: 'Login',
              key: '1',
              children: <h1>test</h1>,
            },
            {
              label: 'register',
              key: '2',
              children: <h1>register</h1>,
            },
          ]}
        />
      </main>
    </>
  );
}
