import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Tabs } from 'antd';
import { GetServerSidePropsContext } from 'next';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main></main>
    </>
  );
}
export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  return {
    redirect: {
      destination: '/dashboard/auth',
      permament: false,
    },
  };
};
